server:
  port: 25000
spring:
  application:
    name: tensquare_config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/bingo_qiqi/ConfigFile.git
  rabbitmq:
    host: 39.105.189.50
  #暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh